Traceback (most recent call last):
  File "/home/ary/Documentos/Aura_Ollama/system_stats_api.py", line 1, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
